/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 base.glb -T 
Files: base.glb [9.19MB] > C:\Users\User\Desktop\public\base-transformed.glb [2.82MB] (69%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Base(props) {
  const { nodes, materials } = useGLTF("/base-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.NoSeat.geometry}
        material={materials["Plastics.002"]}
      />
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials.PaletteMaterial002}
      />
      <mesh
        geometry={nodes.Object_62.geometry}
        material={materials.PaletteMaterial003}
      />
      <mesh
        geometry={nodes.Object_93.geometry}
        material={materials["Seat.002"]}
      />
      <mesh
        geometry={nodes.Object_48.geometry}
        material={materials.PaletteMaterial004}
      />
      <mesh
        geometry={nodes.Object_49.geometry}
        material={materials["Display.002"]}
      />
      <mesh
        geometry={nodes.Object_56.geometry}
        material={materials["Exhaust.002"]}
      />
    </group>
  );
}

useGLTF.preload("/base-transformed.glb");
