/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 base_grey.glb -T 
Files: base_grey.glb [36.25MB] > C:\Users\User\Desktop\optellix-work\configurator\public\base_grey-transformed.glb [4.46MB] (88%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Base_grey(props) {
  const { nodes, materials } = useGLTF("/base_grey-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.NoSeat.geometry}
        material={materials["Plastics.002"]}
      />
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.EngineGuard.geometry}
        material={materials["Copper.002"]}
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials["Black.002"]}
      />
      <mesh
        geometry={nodes.Object_79.geometry}
        material={materials["Tyres.002"]}
      />
      <mesh
        geometry={nodes.Object_62.geometry}
        material={materials.PaletteMaterial002}
      />
      <mesh
        geometry={nodes.Object_93.geometry}
        material={materials["Seat.002"]}
      />
      <mesh
        geometry={nodes.Object_48.geometry}
        material={materials.PaletteMaterial003}
      />
      <mesh
        geometry={nodes.Object_49.geometry}
        material={materials["Display.002"]}
      />
      <mesh
        geometry={nodes.Object_56001.geometry}
        material={materials["Exhaust.002"]}
      />
    </group>
  );
}

useGLTF.preload("/base_grey-transformed.glb");
