/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 base.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Base(props) {
  const { nodes, materials } = useGLTF('/base.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_10.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_12.geometry} material={materials['Rims.002']} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Rims.002']} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_19.geometry} material={materials['Dark_Metal.002']} />
      <mesh geometry={nodes.Object_20.geometry} material={materials['Metal.002']} />
      <mesh geometry={nodes.Object_22.geometry} material={materials['material.001']} />
      <mesh geometry={nodes.Object_24.geometry} material={materials['Dark_Metal.002']} />
      <mesh geometry={nodes.Object_25.geometry} material={materials['Shiny_Metal.001']} />
      <mesh geometry={nodes.Object_27.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_29.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_30.geometry} material={materials['Bronze.002']} />
      <mesh geometry={nodes.Object_32.geometry} material={materials['Metal.002']} />
      <mesh geometry={nodes.Object_36.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_37.geometry} material={materials['Dark_Metal.002']} />
      <mesh geometry={nodes.Object_39.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_4.geometry} material={materials['Dark_Metal.002']} />
      <mesh geometry={nodes.Object_40.geometry} material={materials['Metal.002']} />
      <mesh geometry={nodes.Object_41.geometry} material={materials['Shiny_Metal.001']} />
      <mesh geometry={nodes.Object_43.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_45.geometry} material={materials['Dark_Metal.002']} />
      <mesh geometry={nodes.Object_47.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_49.geometry} material={materials['Display.002']} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['Metal.002']} />
      <mesh geometry={nodes.Object_50.geometry} material={materials['Reflectors.002']} />
      <mesh geometry={nodes.Object_52.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_53.geometry} material={materials['Metal.002']} />
      <mesh geometry={nodes.Object_55.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_56.geometry} material={materials['Exhaust.002']} />
      <mesh geometry={nodes.Object_57.geometry} material={materials['Metal.002']} />
      <mesh geometry={nodes.Object_62.geometry} material={materials['Glass.002']} />
      <mesh geometry={nodes.Object_64.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_65.geometry} material={materials['Indicator_Reflectors.001']} />
      <mesh geometry={nodes.Object_67.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_68.geometry} material={materials['Metal.002']} />
      <mesh geometry={nodes.Object_69.geometry} material={materials['Shiny_Metal.001']} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_70.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_72.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_73.geometry} material={materials['Metal.002']} />
      <mesh geometry={nodes.Object_74.geometry} material={materials['Shiny_Metal.001']} />
      <mesh geometry={nodes.Object_75.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_77.geometry} material={materials['Tyres.002']} />
      <mesh geometry={nodes.Object_79.geometry} material={materials['Tyres.002']} />
      <mesh geometry={nodes.Object_81.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_82.geometry} material={materials['Metal.002']} />
      <mesh geometry={nodes.Object_83.geometry} material={materials['Shiny_Metal.001']} />
      <mesh geometry={nodes.Object_84.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_86.geometry} material={materials['Glass.002']} />
      <mesh geometry={nodes.Object_90.geometry} material={materials['Tail_Light_Reflectors.001']} />
      <mesh geometry={nodes.Object_92.geometry} material={materials['Plastics.002']} />
      <mesh geometry={nodes.Object_93.geometry} material={materials['Seat.002']} />
      <mesh geometry={nodes.Object_95.geometry} material={materials['White.002']} />
      <mesh geometry={nodes.Object_96.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_98.geometry} material={materials['Dark_Metal.003']} />
      <mesh geometry={nodes.Object_30001.geometry} material={materials['Metal.002']} />
      <mesh geometry={nodes.Object_30001_1.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_33004.geometry} material={materials['Black.001']} />
      <mesh geometry={nodes.Object_33004_1.geometry} material={materials['Plastics.004']} />
    </group>
  )
}

useGLTF.preload('/base.glb')
