/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\base_grey.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Base_grey(props) {
  const { nodes, materials } = useGLTF('/base_grey.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4001.geometry} material={materials['Dark_Metal.002']} />
      <mesh geometry={nodes.Object_5001.geometry} material={materials['Metal.002']} />
      <mesh geometry={nodes.Object_7001.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_98001.geometry} material={materials['Dark_Metal.003']} />
      <mesh geometry={nodes.Object_79001.geometry} material={materials['Tyres.002']} />
      <mesh geometry={nodes.Object_77001.geometry} material={materials['Tyres.002']} />
      <mesh geometry={nodes.Object_10001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_12001.geometry} material={materials['Rims.002']} />
      <mesh geometry={nodes.Object_14001.geometry} material={materials['Rims.002']} />
      <mesh geometry={nodes.Object_16001.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_19001.geometry} material={materials['Dark_Metal.002']} />
      <mesh geometry={nodes.Object_20001.geometry} material={materials['Metal.002']} />
      <mesh geometry={nodes.Object_22001.geometry} material={materials['material.001']} />
      <mesh geometry={nodes.Object_24001.geometry} material={materials['Dark_Metal.002']} />
      <mesh geometry={nodes.Object_25001.geometry} material={materials['Shiny_Metal.001']} />
      <mesh geometry={nodes.Object_62001.geometry} material={materials['Glass.002']} />
      <mesh geometry={nodes.Object_64001.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_65001.geometry} material={materials['Indicator_Reflectors.001']} />
      <mesh geometry={nodes.Object_90001.geometry} material={materials['Tail_Light_Reflectors.001']} />
      <mesh geometry={nodes.Object_27001.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_29001.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_30001.geometry} material={materials['Bronze.002']} />
      <mesh geometry={nodes.Object_32002.geometry} material={materials['Metal.002']} />
      <mesh geometry={nodes.Object_92001.geometry} material={materials['Plastics.001']} />
      <mesh geometry={nodes.Object_93001.geometry} material={materials['Seat.002']} />
      <mesh geometry={nodes.Object_36001.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_37001.geometry} material={materials['Dark_Metal.002']} />
      <mesh geometry={nodes.Object_39001.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_40001.geometry} material={materials['Metal.002']} />
      <mesh geometry={nodes.Object_41001.geometry} material={materials['Shiny_Metal.001']} />
      <mesh geometry={nodes.Object_72001.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_73001.geometry} material={materials['Metal.002']} />
      <mesh geometry={nodes.Object_74001.geometry} material={materials['Shiny_Metal.001']} />
      <mesh geometry={nodes.Object_75001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_67001.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_68001.geometry} material={materials['Metal.002']} />
      <mesh geometry={nodes.Object_69001.geometry} material={materials['Shiny_Metal.001']} />
      <mesh geometry={nodes.Object_70001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_81001.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_82001.geometry} material={materials['Metal.002']} />
      <mesh geometry={nodes.Object_83001.geometry} material={materials['Shiny_Metal.001']} />
      <mesh geometry={nodes.Object_84001.geometry} material={materials['material_0.001']} />
      <mesh geometry={nodes.Object_43001.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_45001.geometry} material={materials['Dark_Metal.002']} />
      <mesh geometry={nodes.Object_86001.geometry} material={materials['Glass.002']} />
      <mesh geometry={nodes.Object_47001.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_49001.geometry} material={materials['Display.002']} />
      <mesh geometry={nodes.Object_50001.geometry} material={materials['Reflectors.002']} />
      <mesh geometry={nodes.Object_30002.geometry} material={materials['Metal.002']} />
      <mesh geometry={nodes.Object_30002_1.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_53001.geometry} material={materials['Metal.002']} />
      <mesh geometry={nodes.Object_33002.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_33002_1.geometry} material={materials['Plastics.001']} />
      <mesh geometry={nodes.Object_55001.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Object_56001.geometry} material={materials['Exhaust.002']} />
      <mesh geometry={nodes.Object_57001.geometry} material={materials['Metal.002']} />
      <mesh geometry={nodes.Object_95001.geometry} material={materials['White.002']} />
      <mesh geometry={nodes.Object_96001.geometry} material={materials['Black.002']} />
    </group>
  )
}

useGLTF.preload('/base_grey.glb')
