/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\Engine_Guard.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Engine_Guard(props) {
  const { nodes, materials } = useGLTF('/Engine_Guard.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.EngineGuard.geometry} material={materials['Copper.002']} />
    </group>
  )
}

useGLTF.preload('/Engine_Guard.glb')
