/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Engine_Guard.glb -T 
Files: Engine_Guard.glb [11.64MB] > C:\Users\User\Desktop\public\Engine_Guard-transformed.glb [27.37KB] (100%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Engine_Guard(props) {
  const { nodes, materials } = useGLTF("/Engine_Guard-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.EngineGuard.geometry}
        material={materials["Copper.002"]}
      />
    </group>
  );
}

useGLTF.preload("/Engine_Guard-transformed.glb");
