/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Exhaust.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Exhaust(props) {
  const { nodes, materials } = useGLTF('/Exhaust.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.exhaust.geometry} material={materials['Exhaust.002']} />
    </group>
  )
}

useGLTF.preload('/Exhaust.glb')
