/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Handlebar_Normal.glb -T 
Files: Handlebar_Normal.glb [3.12MB] > C:\Users\User\Desktop\public\Handlebar_Normal-transformed.glb [639.35KB] (79%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Handlebar_Normal(props) {
  const { nodes, materials } = useGLTF("/Handlebar_Normal-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_19002.geometry}
        material={materials.PaletteMaterial002}
      />
      <mesh
        geometry={nodes.Object_19002_1.geometry}
        material={materials["Seat.002"]}
      />
      <mesh
        geometry={nodes.Object_19002_2.geometry}
        material={materials.PaletteMaterial001}
      />
    </group>
  );
}

useGLTF.preload("/Handlebar_Normal-transformed.glb");
