/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 handlebar_Long.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Handlebar_Long(props) {
  const { nodes, materials } = useGLTF('/Handlebar_Long.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.021, -0.011]}>
        <mesh geometry={nodes.Object_19004.geometry} material={materials['Metal.002']} />
        <mesh geometry={nodes.Object_19004_1.geometry} material={materials['Black.002']} />
        <mesh geometry={nodes.Object_19004_2.geometry} material={materials['Dark_Metal.002']} />
        <mesh geometry={nodes.Object_19004_3.geometry} material={materials['Grey.002']} />
        <mesh geometry={nodes.Object_19004_4.geometry} material={materials['material.001']} />
        <mesh geometry={nodes.Object_19004_5.geometry} material={materials['mirrors.002']} />
        <mesh geometry={nodes.Object_19004_6.geometry} material={materials['Seat.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/handlebar_Long.glb')
