/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\Handlebar_Normal.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Handlebar_Normal(props) {
  const { nodes, materials } = useGLTF("/Handlebar_Normal.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_19002.geometry}
        material={materials["Metal.002"]}
      />
      <mesh
        geometry={nodes.Object_19002_1.geometry}
        material={materials["Black.002"]}
      />
      <mesh
        geometry={nodes.Object_19002_2.geometry}
        material={materials["Dark_Metal.002"]}
      />
      <mesh
        geometry={nodes.Object_19002_3.geometry}
        material={materials["Grey.002"]}
      />
      <mesh
        geometry={nodes.Object_19002_4.geometry}
        material={materials["material.001"]}
      />
      <mesh
        geometry={nodes.Object_19002_5.geometry}
        material={materials["mirrors.002"]}
      />
      <mesh
        geometry={nodes.Object_19002_6.geometry}
        material={materials["Seat.002"]}
      />
    </group>
  );
}

useGLTF.preload("/Handlebar_Normal.glb");
