/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\lights.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useThree } from "@react-three/fiber";
import { ACESFilmicToneMapping } from "three";

export function Lights(props) {
  const { nodes, materials } = useGLTF("/lights.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Base001.geometry}
        material={materials.Material}
        position={[0, -0.006, 0.152]}
        scale={[9.202, 4.791, 9.202]}
      />
    </group>
  );
}

useGLTF.preload("/lights.glb");
