/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\LongMudguard.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LongMudguard(props) {
  const { nodes, materials } = useGLTF('/LongMudguard.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.longMudGuard.geometry} material={materials['Plastics.002']} />
    </group>
  )
}

useGLTF.preload('/LongMudguard.glb')
