/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 LongMudguard_grey.glb -T 
Files: LongMudguard_grey.glb [74.82MB] > C:\Users\User\Desktop\public\LongMudguard_grey-transformed.glb [1.65MB] (98%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function LongMudguard_grey(props) {
  const { nodes, materials } = useGLTF("/LongMudguard_grey-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.longMudGuard.geometry}
        material={materials["Plastics.002"]}
      />
    </group>
  );
}

useGLTF.preload("/LongMudguard_grey-transformed.glb");
