/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 NoSeat.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function NoSeat(props) {
  const { nodes, materials } = useGLTF('/NoSeat.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.NoSeat.geometry} material={materials['Plastics.003']} />
    </group>
  )
}

useGLTF.preload('/NoSeat.glb')
