/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\Seat.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Seat(props) {
  const { nodes, materials } = useGLTF('/Seat.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Seat.geometry} material={materials['Seat.003']} />
    </group>
  )
}

useGLTF.preload('/Seat.glb')
