/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Seat.glb -T 
Files: Seat.glb [2.95MB] > C:\Users\User\Desktop\public\Seat-transformed.glb [616.81KB] (79%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Seat(props) {
  const { nodes, materials } = useGLTF("/Seat-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Seat.geometry} material={materials["Seat.003"]} />
    </group>
  );
}

useGLTF.preload("/Seat-transformed.glb");
