/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 SmallMudguard.glb -T 
Files: SmallMudguard.glb [74.85MB] > C:\Users\User\Desktop\public\SmallMudguard-transformed.glb [1.66MB] (98%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function SmallMudguard(props) {
  const { nodes, materials } = useGLTF("/SmallMudguard-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.mudGuard.geometry}
        material={materials["Plastics.002"]}
      />
    </group>
  );
}

useGLTF.preload("/SmallMudguard-transformed.glb");
