/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 SmallMudguard_grey.glb -T 
Files: SmallMudguard_grey.glb [74.82MB] > C:\Users\User\Desktop\public\SmallMudguard_grey-transformed.glb [1.65MB] (98%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function SmallMudguard_grey(props) {
  const { nodes, materials } = useGLTF("/SmallMudguard_grey-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.mudGuard.geometry}
        material={materials["Plastics.002"]}
      />
    </group>
  );
}

useGLTF.preload("/SmallMudguard_grey-transformed.glb");
