/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\stage.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Stage_Props(props) {
  const { nodes, materials } = useGLTF('/stage.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Base.geometry} material={materials['Material.001']} position={[0, -0.006, 0.152]} scale={[9.202, 4.791, 9.202]} />
    </group>
  )
}

useGLTF.preload('/stage.glb')
