/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 WindShield.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function WindShield(props) {
  const { nodes, materials } = useGLTF('/WindShield.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plano027.geometry} material={materials['glass.005']} />
      <mesh geometry={nodes.Plano027_1.geometry} material={materials['Material black plastic']} />
    </group>
  )
}

useGLTF.preload('/WindShield.glb')
