/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 base.glb -T 
Files: base.glb [17.45MB] > C:\Users\User\Desktop\configurator\public\base-transformed.glb [1.19MB] (93%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Base(props) {
  const { nodes, materials } = useGLTF("/base-transformed.glb");
  return (
    <group {...props} dispose={null} receiveShadow position={[0, -0.8, 0]}>
      <mesh
        receiveShadow
        geometry={nodes.Base.geometry}
        material={materials["Material.001"]}
        position={[0, -0.006, 0.152]}
        scale={[9.202, 4.791, 9.202]}
      />
    </group>
  );
}

useGLTF.preload("/base-transformed.glb");
