/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Ducati2.glb -T 
Files: Ducati2.glb [11.9MB] > C:\Users\User\Desktop\configurator\public\Ducati2-transformed.glb [1.32MB] (89%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Ducati2(props) {
  const { nodes, materials } = useGLTF("/Ducati2-transformed.glb");
  return (
    <group {...props} dispose={null} castShadow>
      <mesh
        geometry={nodes.NoSeat.geometry}
        material={materials["Plastics.003"]}
        castShadow
      />
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials.PaletteMaterial002}
      />
      <mesh
        geometry={nodes.Object_62.geometry}
        material={materials.PaletteMaterial003}
      />
      <mesh
        geometry={nodes.Handlebar.geometry}
        material={materials["Seat.002"]}
      />
      <mesh
        geometry={nodes.mudGuard.geometry}
        material={materials["Plastics.002"]}
      />
      <mesh
        geometry={nodes.Object_48.geometry}
        material={materials.PaletteMaterial004}
      />
      <mesh
        geometry={nodes.Object_49.geometry}
        material={materials["Display.002"]}
      />
      <mesh
        geometry={nodes.Object_56.geometry}
        material={materials["Exhaust.002"]}
      />
    </group>
  );
}

useGLTF.preload("/Ducati2-transformed.glb");
