/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ducati.glb -T 
Files: ducati.glb [22.81MB] > C:\Users\User\Desktop\configurator\public\ducati-transformed.glb [2.48MB] (89%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Ducati(props) {
  const { nodes, materials } = useGLTF("/ducati-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Base.geometry}
        material={materials["Material.001"]}
        position={[0, -0.006, 0.152]}
        scale={[9.202, 4.791, 9.202]}
      />
      <mesh
        geometry={nodes.NoSeat.geometry}
        material={materials["Plastics.003"]}
      />
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials.PaletteMaterial002}
      />
      <mesh
        geometry={nodes.Object_62.geometry}
        material={materials.PaletteMaterial003}
      />
      <mesh
        geometry={nodes.Handlebar.geometry}
        material={materials["Seat.002"]}
      />
      <mesh
        geometry={nodes.mudGuard.geometry}
        material={materials["Plastics.002"]}
      />
      <mesh
        geometry={nodes.Object_48.geometry}
        material={materials.PaletteMaterial004}
      />
      <mesh
        geometry={nodes.Object_49.geometry}
        material={materials["Display.002"]}
      />
      <mesh
        geometry={nodes.Object_56.geometry}
        material={materials["Exhaust.002"]}
      />
    </group>
  );
}

useGLTF.preload("/ducati-transformed.glb");
